name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
#jobs

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

  sonar:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Debug SonarQube Secrets
      run: echo "SONAR_HOST_URL=${{ secrets.SONAR_HOST_URL }}"
  

    - name: SonarQube Scan
      run: |
        docker run --rm \
          -e SONAR_HOST_URL="${{ secrets.SONAR_HOST_URL }}" \
          -e SONAR_LOGIN="${{ secrets.SONAR_TOKEN }}" \
          -e SONAR_PROJECT_KEY="nodejs_helloworld" \
          -v $(pwd):/usr/src sonarsource/sonar-scanner-cli
